### ISSUE TITLE
Font families

### ISSUE THREAD

**Issue by hatched-danny** [hatchedlabs/sane-tachyons#3]
Should we leave these as the default browser fonts for now? Are they subject to change? Or should we add avenir and other typography that's used?

https://tachyons.io/docs/typography/font-family/

**Comment by hatched-tom** [comment]
@hatched-danny 

So the sane-tachyons library doesn't include any classes for fonts - they were removed as the original tachyons ones were a bit randomly assembled.

Internally we use a font that looks very similar to the Apple Mac default browser font, but it's a different one :)
